//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPAdo.DonneesV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chambre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chambre()
        {
            this.ChambreGroupeChambres = new HashSet<ChambreGroupeChambre>();
            this.InterventionDetails = new HashSet<InterventionDetail>();
        }
    
        public System.Guid Id { get; set; }
        public string Nom { get; set; }
        public System.Guid Etat { get; set; }
        public string Commentaire { get; set; }
        public System.Guid Hotel { get; set; }
    
        public virtual Etat Etat1 { get; set; }
        public virtual Hotel Hotel1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChambreGroupeChambre> ChambreGroupeChambres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InterventionDetail> InterventionDetails { get; set; }
    }
}
